[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m Attempted to fetch artifact without alias (e.g. "<artifact_name>:v3" or "<artifact_name>:latest")
Traceback (most recent call last):
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/wandb/apis/public.py", line 3223, in _load
    response = self.client.execute(
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 159, in wrapped_fn
    return retrier(*args, **kargs)
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/wandb/apis/public.py", line 188, in execute
    return self._client.execute(*args, **kwargs)
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/wandb/apis/public.py", line 557, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/wandb/apis/public.py", line 2759, in __init__
    self._load()
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/wandb/apis/public.py", line 3235, in _load
    raise ValueError(
ValueError: Attempted to fetch artifact without alias (e.g. "<artifact_name>:v3" or "<artifact_name>:latest")
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/content/nd0821-c2-build-model-workflow-starter/src/basic_cleaning/run.py", line 93, in <module>
    go(args)
  File "/content/nd0821-c2-build-model-workflow-starter/src/basic_cleaning/run.py", line 37, in go
    artifact = run.use_artifact(args.input_artifact)
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2021, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/wandb/apis/public.py", line 557, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/wandb/apis/public.py", line 2759, in __init__
    self._load()
  File "/usr/local/envs/mlflow-5379b70c4c4420dca1e95244cbe993aa6f71772d/lib/python3.9/site-packages/wandb/apis/public.py", line 3235, in _load
    raise ValueError(
wandb.errors.CommError: Attempted to fetch artifact without alias (e.g. "<artifact_name>:v3" or "<artifact_name>:latest")